using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AnimationManager : MonoBehaviour
{
    CharacterController characterController;
    Animator animator;
    Transform target;
    InputManager 覺nputManager;
    GameObject brickTransformParent;
    GameObject player;

    private void Start()
    {
        animator = GetComponent<Animator>();
        target = GetComponent<Transform>();
        覺nputManager = FindObjectOfType<InputManager>();
        characterController = GetComponent<CharacterController>();
        player = GameObject.Find("Player");
        brickTransformParent = player.transform.GetChild(3).gameObject;
    }

    private void Update()
    {

        if (target.hasChanged)
        {
            animator.SetBool("Walk", true);
            target.hasChanged = false;
            if (brickTransformParent.transform.childCount > 0)
            {
                animator.SetBool("Walk", false);
                animator.SetBool("Run", true);
            }
        }
        else
        {
            animator.SetBool("Walk", false);
            animator.SetBool("Run", false);
        }
    }

    public void FallOpen()
    {
        覺nputManager.speed = 0f;
    }
    public void IdleOpen()
    {
        覺nputManager.speed = 4f;
    }
}
